### ISSUE TITLE
weight

### ISSUE THREAD

**Issue by taheritajar** [anuj200199/licenseplatedetection#1]
Hi
thanks for your codes.
how can download your trained weights?

**Comment by anuj200199** [comment]
Hi @shahabta81 , you can use git clone to clone the entire project including the trained weights

**Comment by anuj200199** [comment]
Hi @shahabta81
You can download the project as a zip or else try git lfs

**Comment by anuj200199** [comment]
hi @shahabta81 , was the error solved. If not here is the link to down load the weights 

https://drive.google.com/open?id=1N92YHp5TW_soT-eSLQ_Z5EnqG4uee_De
