### ISSUE TITLE
Not able to download weights!

### ISSUE THREAD

**Issue by shubhamperiwal12** [anuj200199/licenseplatedetection#2]
I am unable to download the pre-trained model weights. The size of weights in zip file is only 100 KB's (I am assuming I am not able to download it properly), resulting in an error on using the weights. Can you please help me with the same

**Comment by anuj200199** [comment]
hi @shubhamperiwal12 , you can use git lfs commands to download the weights properly

**Comment by shubhamperiwal12** [comment]
I tried but its not working. Will it be possible to share the weights file via a drive link?

**Comment by anuj200199** [comment]
hi @shubhamperiwal12  here is the link to the weights file . 
https://drive.google.com/open?id=1N92YHp5TW_soT-eSLQ_Z5EnqG4uee_De
