### ISSUE TITLE
.weight file is broken 

### ISSUE THREAD

**Issue by MrAhmadRaza** [anuj200199/licenseplatedetection#3]
Hi anuj,
Thanks for this contribution, I have cloned this repo and try to run predict.py but following error occurs:

> Traceback (most recent call last):
  File "predict.py", line 63, in <module>
    net = cv2.dnn.readNet(args.weights, args.config)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/dnn/src/darknet/darknet_io.cpp:694: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'ReadDarknetFromWeightsStream'

I changed the weight and cfg file and it works fine. It means, no issue with opencv. I think .weight is broken due to large size. Can you share your file by some other means ?

Thanks

**Comment by anuj200199** [comment]
Hi @MrAhmadRaza,

I am providing this link to help download the weights file. 
https://drive.google.com/file/d/1N92YHp5TW_soT-eSLQ_Z5EnqG4uee_De/view?usp=sharing

**Comment by MrAhmadRaza** [comment]
> Hi @MrAhmadRaza,
> 
> I am providing this link to help download the weights file.
> https://drive.google.com/file/d/1N92YHp5TW_soT-eSLQ_Z5EnqG4uee_De/view?usp=sharing

Hi anuj, 
Thanks for sharing.
