### ISSUE TITLE
nan during training

### ISSUE THREAD

**Issue by rahul-moorkoth** [anuj200199/licenseplatedetection#4]
While training on same dataset I am getting losses as nan. Though I continued training still getting same result after 1500 iteration.

**Comment by anuj200199** [comment]
Hi, I think that you would be training on a CPU. I would prefer training over the GPU for faster convergence. I would recommend using Google Colab for the same.

**Comment by rahul-moorkoth** [comment]
Hi thanks for the quick reply. Will soon update you. I was trying for long time to train yolo on custom dataset.

**Comment by rahul-moorkoth** [comment]
`!./darknet detector test data/NP.data licenseplatedetection/yolov3-tiny-obj.cfg licenseplatedetection/yolo-obj_last.weights /content/darknet/NP_dataset/image\(40\).jpg -dont_show`

The above command on colab didn't predicted anything.

**Comment by rahul-moorkoth** [comment]
`!./darknet detector train data/NP.data cfg/yolov3-tiny-obj.cfg yolov3-tiny.conv.15 -dont_show`

Also this gives error because of brackets.
Cannot load image /content/darknet/NP_dataset/image(107).jpg

**Comment by rahul-moorkoth** [comment]
After removing that image(107) it worked. Thanks
